music_player/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('songs.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
from django.urls import path

from .views import SongListView, ManageListView, upload_song_form, download_youtube_form, delete_song_view, json_songs

app_name = 'songs'

urlpatterns = [
    path('', SongListView.as_view(), name='home'),
    path('manage/', ManageListView.as_view(), name='manage'),
    path('upload/', upload_song_form, name='upload'),
    path('<int:id>/', upload_song_form, name='update'),
    path('download/', download_youtube_form, name='download'),
    path('delete/<int:id>/', delete_song_view, name='delete'),
    path('json_songs/', json_songs, name='json-songs'),
]

songs/models.py
from django.db import models

from PIL import Image

from .audio_tools import validate_is_audio, get_audio_length

class Album(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class Song(models.Model):
    title = models.CharField(max_length=256)
    artist = models.CharField(max_length=256, null=True, blank=True)
    album = models.ForeignKey(Album, on_delete=models.SET_NULL, null=True, blank=True)
    time_length = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    image = models.ImageField(default='img/default.jpg', upload_to='img/', blank=True, null=True)
    image_url = models.CharField(max_length=256, default='media/img/default.jpg', blank=True, null=True)
    audio_file = models.FileField(upload_to='songs', validators=[validate_is_audio], null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.time_length:
            audio_length = get_audio_length(self.audio_file)
            self.time_length = f'{audio_length:.2f}'
        
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

songs/forms.py
from django import forms

from .models import Song

class UploadSongForm(forms.ModelForm):
    album = forms.CharField(max_length=256, required=False, label='Album (Optional)')

    class Meta:
        model = Song
        fields = ['title','artist','audio_file','image']
        labels = {
            'artist':'Artist (Optional)',
            'audio_file':'Song file',
        }

class UpdateSongForm(forms.ModelForm):
    album = forms.CharField(max_length=256, required=False, label='Album (Optional)')

    class Meta:
        model = Song
        fields = ['title','artist','image']
        labels = {
            'artist':'Artist (Optional)',
        }

class DownloadYoutubeForm(forms.Form):
    url = forms.CharField(max_length=256, required=False, label='Paste your youtube link here')

songs/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.http.response import JsonResponse

import pafy
import os

from .models import Song, Album
from .forms import UploadSongForm, DownloadYoutubeForm, UpdateSongForm

def json_songs(request):
    return JsonResponse(list(Song.objects.all().values()), safe=False)

class SongListView(ListView):
    model = Song
    template_name = 'songs/home.html'
    context_object_name = 'songs'

class ManageListView(ListView):
    model = Song
    template_name = 'songs/manage.html'
    context_object_name = 'songs'

def download_youtube_form(request):
    form = DownloadYoutubeForm()

    if request.method == 'POST':
        form = DownloadYoutubeForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            audio = pafy.new(url)
            best = audio.getbestaudio(preftype="m4a")
            path = str(os.getcwd()) + '/media/songs/'
            best.download(filepath=path)
            file = str('songs/' + audio.title + '.m4a')
            song = Song.objects.get_or_create(title=audio.title, artist=audio.author, time_length=audio.length, audio_file=file, image_url=audio.bigthumb)
        return redirect('songs:home')
    
    context = {
        'form':form,
    }

    return render(request, 'songs/download_song.html', context)

def upload_song_form(request, id=0):
    if request.method == 'GET':
        if id == 0:
            form = UploadSongForm()
        else:
            song = Song.objects.get(pk=id)
            form = UpdateSongForm(instance=song)
        context = {'form':form}
        return render(request, 'songs/form_song.html', context)

    if request.method == 'POST':
        if id == 0:
            form = UploadSongForm(request.POST, request.FILES)
        else:
            song = Song.objects.get(pk=id)
            if request.FILES.get('image'):
                song.image = request.FILES.get('image')
            form = UpdateSongForm(request.POST, instance=song)

        if form.is_valid():
            instance = form.save(commit=False)
            album = form.cleaned_data.get('album')
            if album != '':
                music_album = Album.objects.get_or_create(name=album)
                instance.album=music_album[0]
                instance.save()
            else:
                instance.save()
            instance.image_url = 'media/' + instance.image.name
            instance.save()
        return redirect('songs:home')

def delete_song_view(request, id):
    song = Song.objects.get(pk=id)
    song.delete()
    return redirect('songs:manage')

songs/templates/songs/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelementplayer.min.css" rel="stylesheet"/>
    <link href="{% static './css/style.css' %}" rel="stylesheet">
    <title>Music player</title>
</head>
<body>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/c5c4304537.js" crossorigin="anonymous"></script>
    {% block content %}{% endblock %}
</body>
</html>

songs/templates/songs/download_song.html
{% extends 'songs/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
        <div class="jumbotron">
            <h1 class="display-4">Add music from YouTube</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.url | as_crispy_field}}
                <button class="btn btn-success" type="submit">Add</button>
                <a class="btn btn-danger"  href="{% url 'songs:home' %}">Cancel</a>  
            </form>
        </div>
    </div>
</div>

{% endblock %}

songs/templates/songs/form_song.html
{% extends 'songs/home.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
  <div class="col-md-10 offset-md-1 mt-5">
    <div class="jumbotron">
      <h1 class="display-4">Song form</h1>
      <hr class="my-4">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{form.title | as_crispy_field}}
        {{form.artist | as_crispy_field}}
        {{form.album | as_crispy_field}}
        {% if request.path == '/upload/' %}
        {{form.audio_file | as_crispy_field}}
        {% endif %}
        {{form.image | as_crispy_field}}

        <button class="btn btn-success p-3 text-white text-center">
          Submit
        </button>
        <a href="{% url 'songs:home' %}" class="btn btn-danger p-3 text-white text-center">
          Cancel</a>
      </form> 
    </div>
  </div>
</div>
  {% endblock %}

songs/templates/songs/home.html
{% extends 'songs/base.html' %}

{% block content %}

<article class="screen">
  <input type="checkbox" value="None" id="magicButton" name="check" />
  <label class="main" for="magicButton"></label>

  <div class="coverImage">
	  <img class="coverImage" src="{{songs.0.image_url}}">
  </div>
  <div class="search"></div>
  <div class="bodyPlayer"></div>
			<div class="list"><table class="list-table" id="list"></table></div>
				<div class="shadow"></div>
				
				<div class="bar"></div>
				
				<div class="info">
          			<h4 id="title">{{songs.0.title}}</h4>
					<h3 id="artist">{{songs.0.artist}}</h3>
				</div>

        <audio preload="none" id="audio" controls>
			<source src="{{songs.0.audio_file.url}}"/>
        </audio>

				<table class="player">
					<td><input type="checkbox" id="backward" onclick="backward()"/><label class="backward" for="backward"></label></td>
					<td><input type="checkbox" id="play" title="Play" onclick="togglePlayPause()"/><label class="play" for="play"></label></td>
					<td><input type="checkbox" id="forward" onclick="forward()" /><label class="forward" for="forward"></label></td>
				</table>
				
				<table class="footer">
					<td><input type="checkbox" id="love"/><label class="love" for="love"></label></td>
					<td><input type="checkbox" id="shuffle"/><label class="shuffle" for="shuffle"></label></td>
					<td><input type="checkbox" id="repeat" checked /><label class="repeat" for="repeat"></label></td>
					<td>
						<div class="dropleft">
							<button data-toggle="dropdown" href="" type="button" id="options" style="background-color:#111; border:none;"><label style="color:#6d6d6d;" class="options" for="options"></label></button>
							<div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="margin-top:-100px; text-align:left;">
								<a href="{% url 'songs:upload' %}" class="dropdown-item" ><i class="fas fa-cloud-upload-alt"></i> Upload song</a>
								<a href="{% url  'songs:download' %}" class="dropdown-item" ><i class="fab fa-youtube"></i> Get song from YouTube</a>
								<a href="{% url  'songs:manage' %}" class="dropdown-item" ><i class="fas fa-tasks"></i> Manage songs list</a>
							</ul>
						</div>
					</td>
				</table>

				
				<div class="current"><h2 id="current_title">{{songs.0.title}}</h2></div>
				
			
		</article>

<script>
	$(document).ready(function(){
		getSongs();
	});
	
	var audio = document.getElementById('audio');
	var playpause = document.getElementById("play").checked = false;
	var music;
	var currentSongId = 0;
	var lastSongId = 0;

	function getSongs() {
		$.getJSON('json_songs/', function(data) {
			music = data;
			genList();
			$('#0').css("background-color","#ff655c");
			selectSong();
		});
	}

	function genList() {
		$.each(music, function(i,song){
			$('#list').append('<tr class="song" id="'+i+'" onclick="check()"> <td class="nr"> <h5>'+(i+1)+'</h5></td> <td class="title"><h6>'+song.title+'</h6></td> <td class="length"><h5>'+secondsToMinutes(song.time_length)+'</h5></td></tr>')
		});
	}

	function secondsToMinutes(seconds) {
		d = Number(seconds);
		var h = Math.floor(d / 3600);
		var m = Math.floor(d % 3600 / 60);
		var s = Math.floor(d % 3600 % 60);

		var hDisplay = h > 0 ? h + ":" : "";
		var mDisplay = m > 0 ? m + ":" : "0:";
		var sDisplay = s > 0 ? (s < 10 ? "0" : "") + s : "00";
		return hDisplay + mDisplay + sDisplay; 
	}

	function selectSong() {
		$('tr.song').click(function(){
			currentSongId = $(this).attr('id');
			playSong();
		});
	}

	function updateTitle() {
		$('#title').text(music[currentSongId].title);
		$('#'+lastSongId).css("background-color","#222")
		$('#'+currentSongId).css("background-color","#ff655c");
		$('#artist').text(music[currentSongId].artist);
		$('#current_title').text(music[currentSongId].title);
		img_path = music[currentSongId].image_url;
		$('div.coverImage').empty();
		$('div.coverImage').append('<img class="coverImage" src="'+ img_path +'">')
		lastSongId = currentSongId;
	}

	function playSong() {
		var long = music;
		if(currentSongId >= long.length) {
			if(document.getElementById('repeat').checked == true) {
				currentSongId = 0;
				playSong();
				updateTitle();
			} else {
				audio.pause();
				document.getElementById('play').checked = false;
			}
		} else {
			updateTitle();
			var path = 'media/' + music[currentSongId].audio_file;
			$('#audio').attr('src', path);
			togglePlayPause();
			playNextSong();
		}
	}

	function togglePlayPause() {
		if (audio.paused || audio.ended ) {
			playpause.title = "Play";
			audio.play()
		} else {
			playpause.title = "Pause"
			audio.pause()
		}
	}

	function playNextSong() {
		audio.onended = function(){
			if(document.getElementById('shuffle').checked == true) {
				currentSongId = getRandomId(music.length, currentSongId);
			} else {
				currentSongId = currentSongId + 1;
			}
			playSong();
		}
	}

	function forward() {
		if(document.getElementById('shuffle').checked == true) {
				currentSongId = getRandomId(music.length, currentSongId);
		} else {
			currentSongId = currentSongId + 1;
		}
		document.getElementById('play').checked = true;
		playSong();
	}

	function backward() {
		if(currentSongId == 0) {
			currentSongId = music.length - 1;
		} else {
			currentSongId = currentSongId - 1;
		}
		document.getElementById('play').checked = true;
		playSong();
	}

	function getRandomId(length, lastId) {
		var random = 0;
		do {
			random = Math.floor(Math.random() * length);
		} while(random == lastId);
		return random;
	}

	function check() {
		document.getElementById("play").checked = true;
	}

</script>
{% endblock %}

songs/templates/songs/manage.html
{% extends 'songs/base.html' %}

{% block content %}

<div class="container">
    <div class="col-md-10 offset-md-1 mt-5">
    <div class="jumbotron">
        <h1 class="display-4">Songs list manager</h1>
        <p class="lead">You can add, update or delete songs</p>
        <hr class="my-4">
        <a href="{% url 'songs:home' %}" class="btn btn-outline-primary">
            <i class="fas fa-arrow-left"></i> Go back</a>
        <a href="{% url 'songs:upload' %}" class="btn btn-outline-success">
            <i class="fas fa-plus"></i> Upload</a>
        <a href="{% url 'songs:download' %}" class="btn btn-outline-danger">
            <i class="fas fa-plus"></i> Add from YouTube</a>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for song in songs %}
                    <tr>
                        <td>{{song.title}}</td>
                        <td>
                            <a href="{% url 'songs:update' song.id %}" class="btn text-secondary px-0">
                                <i class="far fa-edit"></i>
                            </a>
                            <form action="{% url 'songs:delete' song.id %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn" style="background-color:transparent; border:none;">
                                    <i class="far fa-trash-alt text-danger"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>



{% endblock %}